apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 8080
    hostPort: 8080
  - containerPort: 31000
    hostPort: 31000
  - containerPort: 31010
    hostPort: 31010
  - containerPort: 31020
    hostPort: 31020
  - containerPort: 31021
    hostPort: 31021
- role: worker
- role: worker
- role: worker
