apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 31000 #30000 - 32767
    hostPort: 8080
- role: worker
- role: worker
- role: worker
