applicationSet:
  name: application-set-dev
  project: default
  valueSourceRepo:
    url: https://github.com/V01d42/argocd-sample
    ref: values
    targetRevision: main
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  
  labels:
    env: development
  annotations:
    description: "dev-application-set"
  
  defaults:
    cluster: https://kubernetes.default.svc
  
  applications:
    - name: prometheus
      repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus
      repoRevision: 27.0.0
      path: prometheus
      namespace: prometheus-dev
    - name: grafana
      repoURL: https://grafana.github.io/helm-charts
      chart: grafana
      repoRevision: 9.0.0
      path: grafana
      namespace: grafana-dev

valuesFile:
  - values-dev.yaml