apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-set
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: https://kubernetes.default.svc
        path: "prometheus"
      - cluster: https://kubernetes.default.svc
        path: "grafana"
  template:
    metadata:
      name: '{{path}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/V01d42/argocd-sample
        targetRevision: {{ .Values.targetRevision }}
        path: '{{path}}'
        helm:
          valueFiles:
          {{- with $.Values.valuesFile }}
            {{- toYaml . | nindent 8 }}
          {{- end }}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path}}'
      syncPolicy:
        automated: {}

