argo-cd:
  controller:
    enabled: true

  repoServer:
    enabled: true

  server:
    enabled: true
    service:
      type: NodePort
    initalAdminPassword: admin

  redis:
    enabled: true

  redis-ha:
    enabled: false

  dex:
    enabled: false

  notifications:
    enabled: true

  # Initial Repositories and Applications
  # initialRepos: []
  # initialApplications: []

  grafana:
    enabled: false

  prometheus:
    enabled: false
    kube-state-metrics:
      enabled: false
    pushgateway:
      enabled: false
