prometheus:
  server:
    persistentVolume:
      enabled: false

    service:
      type: NodePort
      servicePort: 80
      nodePort: 31000

  alartmnager:
    persistence:
      enabled: false

grafana:
  service:
    type: NodePort
    nodePort: 31010

  adminUser: admin
  adminPassword: admin

  sidecar:
    datasources:
      enabled: true

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

  dashboards:
    default:
      node-exporter:
        datasource: Prometheus
        url: https://grafana.com/api/dashboards/1860/revisions/32/download

  # namespaceOverride: prometheus
